
Event_CampaignTutorialSkipOn:
	Event_TextBox_Battlemaps	TextID_Battlemaps+35
	Event_TextBox_Battlemaps	0xB03
	Event_End

Event_CampaignTutorialSkipOff:
	Event_TextBox_Battlemaps	TextID_Battlemaps+37
	Event_TextBox_Battlemaps	0xB03
	Event_End
