;UnitList_057.bin
	;Unit Type, X co-ordinate, Y co-ordinate, HP, Ammo, Fuel, AI Type

	@@UnitArmyStart ArmyOrangeStar
	@@UnitBasic UnitNameNeotank,12,3,AIUnitPassive
	@@UnitBasic UnitNameNeotank,11,2,AIUnitPassive
	@@UnitBasic UnitNameNeotank,13,2,AIUnitPassive
	@@UnitBasic UnitNameBattleShip,9,1,AIUnitPassive
	@@UnitBasic UnitNameBattleShip,15,1,AIUnitPassive
	@@UnitBasic UnitNameSub,9,3,AIUnitPassive
	@@UnitBasic UnitNameSub,15,3,AIUnitPassive
	@@UnitBasic UnitNameCruiser,10,4,AIUnitPassive
	@@UnitBasic UnitNameCruiser,14,4,AIUnitPassive
	@@UnitBasic UnitNameAPC,12,1,AIUnitPassive
	@@UnitBasic UnitNameInfantry,11,0,AIUnitPassive
	@@UnitBasic UnitNameInfantry,13,0,AIUnitPassive
	@@UnitBasic UnitNameRocket,11,5,AIUnitPassive
	@@UnitBasic UnitNameRocket,13,5,AIUnitPassive
	@@UnitBasic UnitNameLander,14,5,AIUnitPassive
	@@UnitBasic UnitNameLander,10,5,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,8,2,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,16,2,AIUnitPassive
	@@UnitBasic UnitNameTransportCopter,14,0,AIUnitPassive
	@@UnitBasic UnitNameTransportCopter,10,0,AIUnitPassive
	@@UnitBasic UnitNameFighter,10,1,AIUnitPassive
	@@UnitBasic UnitNameFighter,14,1,AIUnitPassive
	@@UnitBasic UnitNameBomber,10,3,AIUnitPassive
	@@UnitBasic UnitNameBomber,14,3,AIUnitPassive

	@@UnitArmyStart ArmyBlueMoon
	@@UnitBasic UnitNameSub,9,19,AIUnitPassive
	@@UnitBasic UnitNameSub,15,19,AIUnitPassive
	@@UnitBasic UnitNameCruiser,10,18,AIUnitPassive
	@@UnitBasic UnitNameCruiser,14,18,AIUnitPassive
	@@UnitBasic UnitNameBattleShip,9,21,AIUnitPassive
	@@UnitBasic UnitNameBattleShip,15,21,AIUnitPassive
	@@UnitBasic UnitNameNeotank,12,19,AIUnitPassive
	@@UnitBasic UnitNameNeotank,11,20,AIUnitPassive
	@@UnitBasic UnitNameNeotank,13,20,AIUnitPassive
	@@UnitBasic UnitNameAPC,12,21,AIUnitPassive
	@@UnitBasic UnitNameInfantry,11,22,AIUnitPassive
	@@UnitBasic UnitNameInfantry,13,22,AIUnitPassive
	@@UnitBasic UnitNameRocket,11,17,AIUnitPassive
	@@UnitBasic UnitNameRocket,13,17,AIUnitPassive
	@@UnitBasic UnitNameLander,10,17,AIUnitPassive
	@@UnitBasic UnitNameLander,14,17,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,16,20,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,8,20,AIUnitPassive
	@@UnitBasic UnitNameTransportCopter,10,22,AIUnitPassive
	@@UnitBasic UnitNameTransportCopter,14,22,AIUnitPassive
	@@UnitBasic UnitNameFighter,10,21,AIUnitPassive
	@@UnitBasic UnitNameFighter,14,21,AIUnitPassive
	@@UnitBasic UnitNameBomber,10,19,AIUnitPassive
	@@UnitBasic UnitNameBomber,14,19,AIUnitPassive

	@@UnitArmyStart ArmyGreenEarth
	@@UnitBasic UnitNameInfantry,24,12,AIUnitPassive
	@@UnitBasic UnitNameInfantry,24,10,AIUnitPassive
	@@UnitBasic UnitNameNeotank,21,11,AIUnitPassive
	@@UnitBasic UnitNameNeotank,22,12,AIUnitPassive
	@@UnitBasic UnitNameNeotank,22,10,AIUnitPassive
	@@UnitBasic UnitNameAPC,23,11,AIUnitPassive
	@@UnitBasic UnitNameRocket,19,10,AIUnitPassive
	@@UnitBasic UnitNameRocket,19,12,AIUnitPassive
	@@UnitBasic UnitNameLander,19,9,AIUnitPassive
	@@UnitBasic UnitNameLander,19,13,AIUnitPassive
	@@UnitBasic UnitNameCruiser,20,9,AIUnitPassive
	@@UnitBasic UnitNameCruiser,20,13,AIUnitPassive
	@@UnitBasic UnitNameSub,21,8,AIUnitPassive
	@@UnitBasic UnitNameSub,21,14,AIUnitPassive
	@@UnitBasic UnitNameBattleShip,23,8,AIUnitPassive
	@@UnitBasic UnitNameBattleShip,23,14,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,22,7,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,22,15,AIUnitPassive
	@@UnitBasic UnitNameTransportCopter,24,9,AIUnitPassive
	@@UnitBasic UnitNameTransportCopter,24,13,AIUnitPassive
	@@UnitBasic UnitNameFighter,23,9,AIUnitPassive
	@@UnitBasic UnitNameFighter,23,13,AIUnitPassive
	@@UnitBasic UnitNameBomber,21,9,AIUnitPassive
	@@UnitBasic UnitNameBomber,21,13,AIUnitPassive

	@@UnitArmyStart ArmyYellowComet
	@@UnitBasic UnitNameInfantry,0,12,AIUnitPassive
	@@UnitBasic UnitNameInfantry,0,10,AIUnitPassive
	@@UnitBasic UnitNameNeotank,3,11,AIUnitPassive
	@@UnitBasic UnitNameNeotank,2,12,AIUnitPassive
	@@UnitBasic UnitNameNeotank,2,10,AIUnitPassive
	@@UnitBasic UnitNameAPC,1,11,AIUnitPassive
	@@UnitBasic UnitNameRocket,5,10,AIUnitPassive
	@@UnitBasic UnitNameRocket,5,12,AIUnitPassive
	@@UnitBasic UnitNameLander,5,9,AIUnitPassive
	@@UnitBasic UnitNameLander,5,13,AIUnitPassive
	@@UnitBasic UnitNameCruiser,4,9,AIUnitPassive
	@@UnitBasic UnitNameCruiser,4,13,AIUnitPassive
	@@UnitBasic UnitNameSub,3,8,AIUnitPassive
	@@UnitBasic UnitNameSub,3,14,AIUnitPassive
	@@UnitBasic UnitNameBattleShip,1,8,AIUnitPassive
	@@UnitBasic UnitNameBattleShip,1,14,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,2,7,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,2,15,AIUnitPassive
	@@UnitBasic UnitNameTransportCopter,0,9,AIUnitPassive
	@@UnitBasic UnitNameTransportCopter,0,13,AIUnitPassive
	@@UnitBasic UnitNameFighter,1,9,AIUnitPassive
	@@UnitBasic UnitNameFighter,1,13,AIUnitPassive
	@@UnitBasic UnitNameBomber,3,9,AIUnitPassive
	@@UnitBasic UnitNameBomber,3,13,AIUnitPassive

	@@UnitListEnd
