;UnitList_HC_148.bin
	;Unit Type, X co-ordinate, Y co-ordinate, HP, Ammo, Fuel, AI Type

	@@UnitArmyStart ArmyOrangeStar
	@@UnitBasic UnitNameMidTank,23,1,AIUnitPassive
	@@UnitBasic UnitNameArtillery,24,1,AIUnitPassive
	@@UnitBasic UnitNameAPC,21,2,AIUnitPassive
	@@UnitBasic UnitNameAPC,21,3,AIUnitPassive
	@@UnitBasic UnitNameMech,22,2,AIUnitPassive
	@@UnitBasic UnitNameMech,22,3,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,24,2,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,24,3,AIUnitPassive
	@@UnitBasic UnitNameTank,23,4,AIUnitPassive
	@@UnitBasic UnitNameRocket,24,4,AIUnitPassive
	@@UnitBasic UnitNameTank,24,7,AIUnitPassive
	@@UnitBasic UnitNameMissile,22,8,AIUnitPassive
	@@UnitBasic UnitNameMidTank,23,8,AIUnitPassive
	@@UnitBasic UnitNameMidTank,24,8,AIUnitPassive
	@@UnitBasic UnitNameMidTank,24,9,AIUnitPassive
	@@UnitBasic UnitNameMidTank,23,9,AIUnitPassive
	@@UnitBasic UnitNameRocket,22,9,AIUnitPassive
	@@UnitBasic UnitNameTank,24,10,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,22,14,AIUnitPassive
	@@UnitBasic UnitNameRocket,22,15,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,22,16,AIUnitPassive
	@@UnitBasic UnitNameMech,20,16,AIUnitPassive
	@@UnitBasic UnitNameMech,20,15,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,23,15,AIUnitPassive
	@@UnitBasic UnitNameInfantry,20,3,AIUnitPassive
	@@UnitBasic UnitNameInfantry,20,2,AIUnitPassive

	@@UnitArmyStart ArmyBlueMoon
	@@UnitBasic UnitNameBomber,10,0,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,10,2,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,11,2,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,11,3,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,10,3,AIUnitPassive
	@@UnitBasic UnitNameBomber,10,1,AIUnitPassive
	@@UnitBasic UnitNameBomber,11,1,AIUnitPassive
	@@UnitBasic UnitNameFighter,11,0,AIUnitPassive
	@@UnitBasic UnitNameAPC,9,0,AIUnitPassive

	@@UnitArmyStart ArmyGreenEarth
	@@UnitBasic UnitNameInfantry,3,2,AIUnitPassive
	@@UnitBasic UnitNameAPC,4,2,AIUnitPassive
	@@UnitBasic UnitNameNeotank,3,3,AIUnitActive
	@@UnitBasic UnitNameMech,4,3,AIUnitPassive
	@@UnitBasic UnitNameArtillery,5,5,AIUnitPassive
	@@UnitBasic UnitNameRocket,8,6,AIUnitPassive
	@@UnitBasic UnitNameRocket,12,7,AIUnitPassive
	@@UnitBasic UnitNameRocket,12,10,AIUnitPassive
	@@UnitBasic UnitNameMissile,7,7,AIUnitPassive
	@@UnitBasic UnitNameMissile,11,11,AIUnitPassive
	@@UnitBasic UnitNameRocket,5,12,AIUnitActive
	@@UnitBasic UnitNameNeotank,0,7,AIUnitActive
	@@UnitBasic UnitNameMidTank,0,8,AIUnitActive
	@@UnitBasic UnitNameMidTank,0,9,AIUnitActive
	@@UnitBasic UnitNameNeotank,0,10,AIUnitActive
	@@UnitBasic UnitNameTank,1,7,AIUnitActive
	@@UnitBasic UnitNameTank,1,8,AIUnitActive
	@@UnitBasic UnitNameTank,1,9,AIUnitActive
	@@UnitBasic UnitNameTank,1,10,AIUnitActive
	@@UnitBasic UnitNameAnti-Air,2,7,AIUnitActive
	@@UnitBasic UnitNameAnti-Air,2,8,AIUnitActive
	@@UnitBasic UnitNameAnti-Air,2,9,AIUnitActive
	@@UnitBasic UnitNameAnti-Air,2,10,AIUnitActive
	@@UnitBasic UnitNameBattleCopter,2,15,AIUnitActive
	@@UnitBasic UnitNameBattleCopter,2,16,AIUnitActive
	@@UnitBasic UnitNameBomber,0,16,AIUnitActive
	@@UnitBasic UnitNameBomber,0,17,AIUnitActive
	@@UnitBasic UnitNameBomber,1,17,AIUnitActive
	@@UnitBasic UnitNameBattleCopter,4,15,AIUnitActive
	@@UnitBasic UnitNameBattleCopter,4,16,AIUnitActive
	@@UnitBasic UnitNameNeotank,0,12,AIUnitActive
	@@UnitBasic UnitNameNeotank,0,13,AIUnitActive
	@@UnitBasic UnitNameMidTank,1,12,AIUnitActive
	@@UnitBasic UnitNameMidTank,1,13,AIUnitActive
	@@UnitBasic UnitNameMissile,2,5,AIUnitPassive
	@@UnitBasic UnitNameArtillery,15,12,AIUnitPassive
	@@UnitBasic UnitNameBomber,1,16,AIUnitActive
	@@UnitBasic UnitNameTank,13,9,AIUnitActive
	@@UnitBasic UnitNameTank,13,8,AIUnitActive
	@@UnitBasic UnitNameAnti-Air,12,9,AIUnitActive
	@@UnitBasic UnitNameAnti-Air,12,8,AIUnitActive
	@@UnitBasic UnitNameRecon,14,5,AIUnitActive

	@@UnitListEnd
