;UnitList_HC_164.bin
	;Unit Type, X co-ordinate, Y co-ordinate, HP, Ammo, Fuel, AI Type

	@@UnitArmyStart ArmyOrangeStar
	@@UnitBasic UnitNameTank,23,24,AIUnitPassive
	@@UnitBasic UnitNameRecon,23,26,AIUnitPassive
	@@UnitBasic UnitNameAPC,24,24,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,23,25,AIUnitPassive
	@@UnitBasic UnitNameFighter,24,23,AIUnitPassive
	@@UnitBasic UnitNameFighter,22,25,AIUnitPassive
	@@UnitBasic UnitNameBomber,22,26,AIUnitPassive
	@@UnitBasic UnitNameBomber,25,23,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,23,23,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,22,23,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,22,24,AIUnitPassive
	@@UnitBasic UnitNameFighter,24,25,AIUnitPassive
	@@UnitBasic UnitNameMidTank,26,27,AIUnitPassive
	@@UnitBasic UnitNameInfantry,26,25,AIUnitPassive
	@@UnitBasic UnitNameMech,25,26,AIUnitPassive
	@@UnitBasic UnitNameTransportCopter,26,26,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,25,24,AIUnitPassive

	@@UnitArmyStart ArmyBlueMoon
	@@UnitBasic UnitNameMech,9,12,AIUnitPassive
	@@UnitBasic UnitNameMech,11,11,AIUnitPassive
	@@UnitBasic UnitNameMech,12,10,AIUnitPassive
	@@UnitBasic UnitNameAPC,9,11,AIUnitPassive
	@@UnitBasic UnitNameRocket,10,10,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,12,11,AIUnitPassive
	@@UnitBasic UnitNameMissile,11,12,AIUnitPassive

	@@UnitArmyStart ArmyGreenEarth
	@@UnitBasic UnitNameInfantry,1,4,AIUnitPassive
	@@UnitBasic UnitNameTank,1,2,AIUnitActive
	@@UnitBasic UnitNameTank,2,1,AIUnitActive
	@@UnitBasic UnitNameTank,20,3,AIUnitActive
	@@UnitBasic UnitNameTank,15,18,AIUnitActive
	@@UnitBasic UnitNameArtillery,21,3,AIUnitActive
	@@UnitBasic UnitNameRocket,9,4,AIUnitPassive
	@@UnitBasic UnitNameRocket,14,4,AIUnitPassive
	@@UnitBasic UnitNameRocket,3,12,AIUnitPassive
	@@UnitBasic UnitNameRocket,18,10,AIUnitPassive
	@@UnitBasic UnitNameRocket,11,18,AIUnitActive
	@@UnitBasic UnitNameAnti-Air,2,2,AIUnitActive
	@@UnitBasic UnitNameAnti-Air,19,4,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,14,18,AIUnitActive
	@@UnitBasic UnitNameMissile,13,18,AIUnitActive
	@@UnitBasic UnitNameMissile,19,2,AIUnitPassive
	@@UnitBasic UnitNameFighter,25,7,AIUnitActive
	@@UnitBasic UnitNameBomber,25,8,AIUnitActive
	@@UnitBasic UnitNameBomber,7,27,AIUnitActive
	@@UnitBasic UnitNameBomber,8,27,AIUnitActive
	@@UnitBasic UnitNameBattleCopter,27,8,AIUnitActive
	@@UnitBasic UnitNameBattleCopter,7,26,AIUnitActive
	@@UnitBasic UnitNameBattleCopter,8,26,AIUnitActive
	@@UnitBasic UnitNameBattleCopter,26,8,AIUnitActive
	@@UnitBasic UnitNameBattleCopter,1,0,AIUnitActive
	@@UnitBasic UnitNameBattleCopter,0,1,AIUnitActive
	@@UnitBasic UnitNameInfantry,18,3,AIUnitPassive
	@@UnitBasic UnitNameMidTank,19,3,AIUnitActive
	@@UnitBasic UnitNameMissile,9,1,AIUnitPassive
	@@UnitBasic UnitNameMissile,3,15,AIUnitPassive
	@@UnitBasic UnitNameMissile,15,3,AIUnitPassive
	@@UnitBasic UnitNameFighter,26,7,AIUnitActive
	@@UnitBasic UnitNameBomber,24,8,AIUnitActive
	@@UnitBasic UnitNameBomber,6,27,AIUnitActive
	@@UnitBasic UnitNameMidTank,14,19,AIUnitActive
	@@UnitBasic UnitNameNeotank,19,10,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,18,11,AIUnitPassive
	@@UnitBasic UnitNameMidTank,1,1,AIUnitActive
	@@UnitBasic UnitNameInfantry,6,7,AIUnitActive
	@@UnitBasic UnitNameInfantry,6,15,AIUnitActive
	@@UnitBasic UnitNameInfantry,15,15,AIUnitActive
	@@UnitBasic UnitNameInfantry,15,7,AIUnitActive
	@@UnitBasic UnitNameTank,23,9,AIUnitActive
	@@UnitBasic UnitNameRecon,22,9,AIUnitActive
	@@UnitBasic UnitNameArtillery,24,9,AIUnitActive
	@@UnitBasic UnitNameMissile,2,4,AIUnitPassive

	@@UnitListEnd
