;UnitList_HC_157.bin
	;Unit Type, X co-ordinate, Y co-ordinate, HP, Ammo, Fuel, AI Type

	@@UnitArmyStart ArmyOrangeStar
	@@UnitBasic UnitNameMech,4,3,AIUnitPassive
	@@UnitBasic UnitNameMech,1,12,AIUnitPassive
	@@UnitBasic UnitNameMech,17,10,AIUnitPassive
	@@UnitBasic UnitNameMech,15,13,AIUnitPassive
	@@UnitBasic UnitNameMech,13,15,AIUnitPassive
	@@UnitBasic UnitNameMidTank,11,1,AIUnitPassive
	@@UnitBasic UnitNameRecon,1,6,AIUnitPassive
	@@UnitBasic UnitNameAPC,15,19,AIUnitPassive
	@@UnitBasic UnitNameArtillery,1,10,AIUnitPassive
	@@UnitBasic UnitNameRocket,2,8,AIUnitPassive
	@@UnitBasic UnitNameArtillery,6,0,AIUnitPassive
	@@UnitBasic UnitNameRocket,16,10,AIUnitPassive
	@@UnitBasic UnitNameArtillery,14,14,AIUnitPassive
	@@UnitBasic UnitNameRocket,16,14,AIUnitPassive
	@@UnitBasic UnitNameRocket,16,8,AIUnitPassive
	@@UnitBasic UnitNameRocket,1,9,AIUnitPassive
	@@UnitBasic UnitNameRocket,3,7,AIUnitPassive
	@@UnitBasic UnitNameRocket,5,2,AIUnitPassive
	@@UnitBasic UnitNameRocket,12,1,AIUnitPassive
	@@UnitBasic UnitNameRocket,14,13,AIUnitPassive
	@@UnitBasic UnitNameRecon,17,9,AIUnitPassive
	@@UnitBasic UnitNameAPC,1,3,AIUnitPassive
	@@UnitBasic UnitNameArtillery,12,2,AIUnitPassive
	@@UnitBasic UnitNameMidTank,13,1,AIUnitPassive
	@@UnitBasic UnitNameMech,6,6,AIUnitPassive
	@@UnitBasic UnitNameMech,15,8,AIUnitPassive

	@@UnitArmyStart ArmyBlueMoon
	@@UnitBasic UnitNameMech,5,15,AIUnitPassive
	@@UnitBasic UnitNameMech,6,15,AIUnitPassive
	@@UnitBasic UnitNameMech,7,15,AIUnitPassive
	@@UnitBasic UnitNameInfantry,5,16,AIUnitPassive
	@@UnitBasic UnitNameInfantry,6,16,AIUnitPassive
	@@UnitBasic UnitNameInfantry,7,16,AIUnitPassive
	@@UnitBasic UnitNameMidTank,3,19,AIUnitPassive
	@@UnitBasic UnitNameMidTank,3,18,AIUnitPassive
	@@UnitBasic UnitNameMidTank,4,17,AIUnitPassive
	@@UnitBasic UnitNameNeotank,5,17,AIUnitPassive
	@@UnitBasic UnitNameNeotank,6,17,AIUnitPassive
	@@UnitBasic UnitNameNeotank,7,17,AIUnitPassive
	@@UnitBasic UnitNameNeotank,8,17,AIUnitPassive
	@@UnitBasic UnitNameMidTank,9,18,AIUnitPassive
	@@UnitBasic UnitNameMidTank,9,19,AIUnitPassive
	@@UnitBasic UnitNameRecon,3,17,AIUnitPassive
	@@UnitBasic UnitNameRecon,9,17,AIUnitPassive
	@@UnitBasic UnitNameTank,5,19,AIUnitPassive
	@@UnitBasic UnitNameTank,6,19,AIUnitPassive
	@@UnitBasic UnitNameTank,6,18,AIUnitPassive
	@@UnitBasic UnitNameTank,7,19,AIUnitPassive
	@@UnitBasic UnitNameAPC,8,16,AIUnitPassive
	@@UnitBasic UnitNameAPC,4,16,AIUnitPassive
	@@UnitBasic UnitNameArtillery,8,18,AIUnitPassive
	@@UnitBasic UnitNameArtillery,4,18,AIUnitPassive
	@@UnitBasic UnitNameRocket,4,19,AIUnitPassive
	@@UnitBasic UnitNameRocket,8,19,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,9,16,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,3,16,AIUnitPassive
	@@UnitBasic UnitNameNeotank,5,18,AIUnitPassive
	@@UnitBasic UnitNameNeotank,7,18,AIUnitPassive
	@@UnitBasic UnitNameRecon,8,12,AIUnitPassive
	@@UnitBasic UnitNameRecon,7,12,AIUnitPassive
	@@UnitBasic UnitNameTank,8,10,AIUnitPassive
	@@UnitBasic UnitNameTank,9,10,AIUnitPassive
	@@UnitBasic UnitNameTank,9,9,AIUnitPassive
	@@UnitBasic UnitNameTank,8,9,AIUnitPassive
	@@UnitBasic UnitNameArtillery,8,13,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,7,13,AIUnitPassive

	@@UnitListEnd
