;UnitList_HC_158.bin
	;Unit Type, X co-ordinate, Y co-ordinate, HP, Ammo, Fuel, AI Type

	@@UnitArmyStart ArmyOrangeStar
	@@UnitBasic UnitNameInfantry,5,27,AIUnitPassive
	@@UnitBasic UnitNameInfantry,5,28,AIUnitPassive
	@@UnitBasic UnitNameInfantry,5,29,AIUnitPassive
	@@UnitBasic UnitNameBomber,0,27,AIUnitPassive
	@@UnitBasic UnitNameBomber,0,28,AIUnitPassive
	@@UnitBasic UnitNameBomber,0,29,AIUnitPassive
	@@UnitBasic UnitNameBomber,1,27,AIUnitPassive
	@@UnitBasic UnitNameBomber,1,28,AIUnitPassive
	@@UnitBasic UnitNameBomber,1,29,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,3,27,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,3,28,AIUnitPassive
	@@UnitBasic UnitNameBattleCopter,3,29,AIUnitPassive
	@@UnitBasic UnitNameTransportCopter,2,27,AIUnitPassive
	@@UnitBasic UnitNameTransportCopter,2,28,AIUnitPassive
	@@UnitBasic UnitNameTransportCopter,2,29,AIUnitPassive
	@@UnitBasic UnitNameMidTank,3,13,AIUnitPassive
	@@UnitBasic UnitNameMidTank,5,13,AIUnitPassive
	@@UnitBasic UnitNameArtillery,4,14,AIUnitPassive

	@@UnitArmyStart ArmyBlueMoon
	@@UnitBasic UnitNameMech,4,3,AIUnitPassive
	@@UnitBasic UnitNameMech,3,3,AIUnitPassive
	@@UnitBasic UnitNameMech,5,3,AIUnitPassive
	@@UnitBasic UnitNameMidTank,2,0,AIUnitPassive
	@@UnitBasic UnitNameNeotank,3,0,AIUnitPassive
	@@UnitBasic UnitNameNeotank,4,0,AIUnitPassive
	@@UnitBasic UnitNameNeotank,5,0,AIUnitPassive
	@@UnitBasic UnitNameMidTank,6,0,AIUnitPassive
	@@UnitBasic UnitNameMidTank,15,16,AIUnitActive
	@@UnitBasic UnitNameMidTank,16,22,AIUnitActive
	@@UnitBasic UnitNameTank,2,1,AIUnitActive
	@@UnitBasic UnitNameTank,3,1,AIUnitActive
	@@UnitBasic UnitNameTank,5,1,AIUnitActive
	@@UnitBasic UnitNameTank,6,1,AIUnitActive
	@@UnitBasic UnitNameTank,16,17,AIUnitActive
	@@UnitBasic UnitNameRecon,19,21,AIUnitPassive
	@@UnitBasic UnitNameAPC,4,2,AIUnitPassive
	@@UnitBasic UnitNameArtillery,2,2,AIUnitPassive
	@@UnitBasic UnitNameArtillery,3,2,AIUnitPassive
	@@UnitBasic UnitNameArtillery,18,21,AIUnitPassive
	@@UnitBasic UnitNameRocket,18,14,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,19,16,AIUnitActive
	@@UnitBasic UnitNameAnti-Air,15,22,AIUnitActive
	@@UnitBasic UnitNameMissile,0,3,AIUnitPassive
	@@UnitBasic UnitNameMissile,15,1,AIUnitPassive
	@@UnitBasic UnitNameMissile,16,14,AIUnitPassive
	@@UnitBasic UnitNameInfantry,12,22,AIUnitPassive
	@@UnitBasic UnitNameInfantry,11,22,AIUnitPassive
	@@UnitBasic UnitNameRocket,15,2,AIUnitPassive
	@@UnitBasic UnitNameTank,15,5,AIUnitPassive
	@@UnitBasic UnitNameInfantry,2,3,AIUnitPassive
	@@UnitBasic UnitNameInfantry,6,3,AIUnitPassive
	@@UnitBasic UnitNameAnti-Air,4,17,AIUnitPassive
	@@UnitBasic UnitNameTank,18,2,AIUnitPassive
	@@UnitBasic UnitNameTank,18,4,AIUnitPassive
	@@UnitBasic UnitNameTank,18,3,AIUnitPassive
	@@UnitBasic UnitNameTank,9,20,AIUnitPassive
	@@UnitBasic UnitNameNeotank,17,13,AIUnitPassive
	@@UnitBasic UnitNameMidTank,6,24,AIUnitActive
	@@UnitBasic UnitNameArtillery,7,24,AIUnitActive
	@@UnitBasic UnitNameMidTank,5,7,AIUnitActive
	@@UnitBasic UnitNameMidTank,4,7,AIUnitActive
	@@UnitBasic UnitNameArtillery,5,2,AIUnitPassive
	@@UnitBasic UnitNameArtillery,6,2,AIUnitPassive
	@@UnitBasic UnitNameTank,7,6,AIUnitActive
	@@UnitBasic UnitNameTank,6,6,AIUnitActive
	@@UnitBasic UnitNameMidTank,4,1,AIUnitPassive

	@@UnitListEnd
