;AWDSUnitList_070.bin
	;Unit Type, X co-ordinate, Y co-ordinate, HP, Ammo, Fuel, AI Type
AWDSUnitList_070:
	@@UnitArmyStart ArmyOrangeStar
	@@UnitBasic Unit_Infantry,1,1,AIUnitDefensive
	@@UnitBasic Unit_Infantry,0,2,AIUnitDefensive
	@@UnitBasic Unit_Infantry,2,0,AIUnitDefensive
	@@UnitBasic Unit_Mech,1,2,AIUnitDefensive
	@@UnitBasic Unit_Mech,2,1,AIUnitDefensive
	@@UnitBasic Unit_APC,4,12,AIUnitDefensive
	@@UnitBasic Unit_APC,9,4,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,2,4,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,4,2,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,3,3,AIUnitDefensive
	@@UnitBasic Unit_Missiles,2,2,AIUnitDefensive
	@@UnitBasic Unit_Fighter,6,5,AIUnitDefensive
	@@UnitBasic Unit_Fighter,5,6,AIUnitDefensive
	@@UnitBasic Unit_Fighter,6,6,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,0,9,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,9,0,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,0,0,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,16,17,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,15,15,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,14,14,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,16,16,AIUnitDefensive
	@@UnitBasic Unit_Lander,5,4,AIUnitDefensive
	@@UnitBasic Unit_Lander,4,5,AIUnitDefensive
	@@UnitBasic Unit_BlackBoat,0,8,AIUnitDefensive
	@@UnitBasic Unit_BlackBoat,8,0,AIUnitDefensive
	@@UnitBasic Unit_Carrier,8,8,AIUnitDefensive
	@@UnitBasic Unit_Carrier,3,8,AIUnitDefensive
	@@UnitBasic Unit_Carrier,8,3,AIUnitDefensive

	@@UnitArmyStart ArmyBlueMoon
	@@UnitBasic Unit_Infantry,32,0,AIUnitDefensive
	@@UnitBasic Unit_Infantry,33,1,AIUnitDefensive
	@@UnitBasic Unit_Infantry,34,2,AIUnitDefensive
	@@UnitBasic Unit_Mech,32,1,AIUnitDefensive
	@@UnitBasic Unit_Mech,33,2,AIUnitDefensive
	@@UnitBasic Unit_APC,30,12,AIUnitDefensive
	@@UnitBasic Unit_APC,24,4,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,31,3,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,30,2,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,32,4,AIUnitDefensive
	@@UnitBasic Unit_Missiles,32,2,AIUnitDefensive
	@@UnitBasic Unit_Fighter,28,5,AIUnitDefensive
	@@UnitBasic Unit_Fighter,29,6,AIUnitDefensive
	@@UnitBasic Unit_Fighter,28,6,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,34,0,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,25,0,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,34,9,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,17,18,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,19,15,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,20,14,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,18,16,AIUnitDefensive
	@@UnitBasic Unit_Lander,30,5,AIUnitDefensive
	@@UnitBasic Unit_Lander,29,4,AIUnitDefensive
	@@UnitBasic Unit_BlackBoat,34,8,AIUnitDefensive
	@@UnitBasic Unit_BlackBoat,26,0,AIUnitDefensive
	@@UnitBasic Unit_Carrier,26,8,AIUnitDefensive
	@@UnitBasic Unit_Carrier,31,8,AIUnitDefensive
	@@UnitBasic Unit_Carrier,26,3,AIUnitDefensive

	@@UnitArmyStart ArmyGreenEarth
	@@UnitBasic Unit_Infantry,32,34,AIUnitDefensive
	@@UnitBasic Unit_Infantry,33,33,AIUnitDefensive
	@@UnitBasic Unit_Infantry,34,32,AIUnitDefensive
	@@UnitBasic Unit_Mech,33,32,AIUnitDefensive
	@@UnitBasic Unit_Mech,32,33,AIUnitDefensive
	@@UnitBasic Unit_APC,25,30,AIUnitDefensive
	@@UnitBasic Unit_APC,30,22,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,31,31,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,30,32,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,32,30,AIUnitDefensive
	@@UnitBasic Unit_Missiles,32,32,AIUnitDefensive
	@@UnitBasic Unit_Fighter,28,28,AIUnitDefensive
	@@UnitBasic Unit_Fighter,28,29,AIUnitDefensive
	@@UnitBasic Unit_Fighter,29,28,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,34,34,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,25,34,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,34,25,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,17,16,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,19,19,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,20,20,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,18,18,AIUnitDefensive
	@@UnitBasic Unit_Lander,29,30,AIUnitDefensive
	@@UnitBasic Unit_Lander,30,29,AIUnitDefensive
	@@UnitBasic Unit_BlackBoat,34,26,AIUnitDefensive
	@@UnitBasic Unit_BlackBoat,26,34,AIUnitDefensive
	@@UnitBasic Unit_Carrier,26,26,AIUnitDefensive
	@@UnitBasic Unit_Carrier,26,31,AIUnitDefensive
	@@UnitBasic Unit_Carrier,31,26,AIUnitDefensive

	@@UnitArmyStart ArmyYellowComet
	@@UnitBasic Unit_Infantry,2,34,AIUnitDefensive
	@@UnitBasic Unit_Infantry,1,33,AIUnitDefensive
	@@UnitBasic Unit_Infantry,0,32,AIUnitDefensive
	@@UnitBasic Unit_Mech,2,33,AIUnitDefensive
	@@UnitBasic Unit_Mech,1,32,AIUnitDefensive
	@@UnitBasic Unit_APC,4,22,AIUnitDefensive
	@@UnitBasic Unit_APC,9,30,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,3,31,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,4,32,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,2,30,AIUnitDefensive
	@@UnitBasic Unit_Missiles,2,32,AIUnitDefensive
	@@UnitBasic Unit_Fighter,6,28,AIUnitDefensive
	@@UnitBasic Unit_Fighter,6,29,AIUnitDefensive
	@@UnitBasic Unit_Fighter,5,28,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,0,34,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,0,25,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,9,34,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,18,17,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,15,19,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,14,20,AIUnitDefensive
	@@UnitBasic Unit_Blackbomb,16,18,AIUnitDefensive
	@@UnitBasic Unit_Lander,5,30,AIUnitDefensive
	@@UnitBasic Unit_Lander,4,29,AIUnitDefensive
	@@UnitBasic Unit_BlackBoat,8,34,AIUnitDefensive
	@@UnitBasic Unit_BlackBoat,0,26,AIUnitDefensive
	@@UnitBasic Unit_Carrier,8,31,AIUnitDefensive
	@@UnitBasic Unit_Carrier,8,26,AIUnitDefensive
	@@UnitBasic Unit_Carrier,3,26,AIUnitDefensive

	@@UnitListEnd
