;AWDSUnitList_HC_237.bin
	;Unit Type, X co-ordinate, Y co-ordinate, HP, Ammo, Fuel, AI Type
AWDSUnitList_HC_237:
	@@UnitArmyStart ArmyOrangeStar
	@@UnitBasic Unit_Stealth,5,11,AIUnitDefensive
	@@UnitBasic Unit_Stealth,6,11,AIUnitDefensive
	@@UnitBasic Unit_Stealth,7,11,AIUnitDefensive
	@@UnitBasic Unit_Stealth,23,12,AIUnitDefensive
	@@UnitBasic Unit_Stealth,23,13,AIUnitDefensive
	@@UnitBasic Unit_Stealth,22,12,AIUnitDefensive
	@@UnitBasic Unit_Stealth,22,13,AIUnitDefensive
	@@UnitBasic Unit_Infantry,2,1,AIUnitDefensive
	@@UnitBasic Unit_Mech,0,1,AIUnitDefensive
	@@UnitBasic Unit_Tank,0,5,AIUnitDefensive
	@@UnitBasic Unit_APC,1,2,AIUnitDefensive
	@@UnitBasic Unit_APC,1,4,AIUnitDefensive
	@@UnitBasic Unit_Artillery,0,6,AIUnitDefensive
	@@UnitBasic Unit_Rockets,0,7,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,0,3,AIUnitDefensive
	@@UnitBasic Unit_Fighter,6,5,AIUnitDefensive
	@@UnitBasic Unit_Fighter,6,4,AIUnitDefensive
	@@UnitBasic Unit_Fighter,5,5,AIUnitDefensive
	@@UnitBasic Unit_Fighter,5,4,AIUnitDefensive
	@@UnitBasic Unit_Bomber,4,3,AIUnitDefensive
	@@UnitBasic Unit_BattleCopter,3,3,AIUnitDefensive
	@@UnitBasic Unit_BattleCopter,4,2,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,1,1,AIUnitDefensive
	@@UnitBasic Unit_BattleShip,4,1,AIUnitDefensive
	@@UnitBasic Unit_Cruiser,3,2,AIUnitDefensive
	@@UnitBasic Unit_Lander,5,1,AIUnitDefensive
	@@UnitBasic Unit_Sub,2,3,AIUnitDefensive
	@@UnitBasic Unit_Carrier,5,11,AIUnitDefensive
	@@UnitBasic Unit_Carrier,6,11,AIUnitDefensive
	@@UnitBasic Unit_Carrier,7,11,AIUnitDefensive
	@@UnitBasic Unit_Carrier,23,12,AIUnitDefensive
	@@UnitBasic Unit_Carrier,23,13,AIUnitDefensive
	@@UnitBasic Unit_Carrier,22,12,AIUnitDefensive
	@@UnitBasic Unit_Carrier,22,13,AIUnitDefensive

	@@UnitArmyStart ArmyBlueMoon
	@@UnitBasic Unit_Infantry,25,11,AIUnitDefensive
	@@UnitBasic Unit_Mech,25,15,AIUnitDefensive
	@@UnitBasic Unit_Tank,3,11,AIUnitDefensive
	@@UnitBasic Unit_MidTank,7,15,AIUnitDefensive
	@@UnitBasic Unit_Neotank,20,11,AIUnitDefensive
	@@UnitBasic Unit_Artillery,12,0,AIUnitDefensive
	@@UnitBasic Unit_Artillery,1,13,AIUnitDefensive
	@@UnitBasic Unit_Rockets,13,1,AIUnitDefensive
	@@UnitBasic Unit_Rockets,14,12,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,13,11,AIUnitDefensive
	@@UnitBasic Unit_AntiAir,23,1,AIUnitDefensive
	@@UnitBasic Unit_Missiles,24,2,AIUnitDefensive
	@@UnitBasic Unit_Missiles,20,12,AIUnitDefensive
	@@UnitBasic Unit_Fighter,24,3,AIUnitDefensive
	@@UnitBasic Unit_Bomber,25,4,AIUnitDefensive
	@@UnitBasic Unit_BattleCopter,23,3,AIUnitDefensive
	@@UnitBasic Unit_BattleCopter,24,4,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,11,13,AIUnitDefensive
	@@UnitBasic Unit_BattleShip,15,6,AIUnitDefensive
	@@UnitBasic Unit_BattleShip,15,8,AIUnitDefensive
	@@UnitBasic Unit_Cruiser,5,12,AIUnitDefensive
	@@UnitBasic Unit_Cruiser,6,12,AIUnitDefensive
	@@UnitBasic Unit_Cruiser,7,12,AIUnitDefensive
	@@UnitBasic Unit_Cruiser,15,7,AIUnitDefensive
	@@UnitBasic Unit_Sub,14,7,AIUnitDefensive
	@@UnitBasic Unit_BlackBoat,7,14,AIUnitDefensive
	@@UnitBasic Unit_BlackBoat,16,7,AIUnitDefensive
	@@UnitBasic Unit_BlackBoat,19,2,AIUnitDefensive
	@@UnitBasic Unit_BlackBoat,19,13,AIUnitDefensive

	@@UnitListEnd
