;AWDSUnitList_063.bin
	;Unit Type, X co-ordinate, Y co-ordinate, HP, Ammo, Fuel, AI Type
AWDSUnitList_063:
	@@UnitArmyStart ArmyOrangeStar
	@@UnitBasic Unit_Infantry,11,0,AIUnitDefensive
	@@UnitBasic Unit_Infantry,13,0,AIUnitDefensive
	@@UnitBasic Unit_Neotank,12,3,AIUnitDefensive
	@@UnitBasic Unit_Neotank,11,2,AIUnitDefensive
	@@UnitBasic Unit_Neotank,13,2,AIUnitDefensive
	@@UnitBasic Unit_APC,12,1,AIUnitDefensive
	@@UnitBasic Unit_Rockets,11,5,AIUnitDefensive
	@@UnitBasic Unit_Rockets,13,5,AIUnitDefensive
	@@UnitBasic Unit_Fighter,10,1,AIUnitDefensive
	@@UnitBasic Unit_Fighter,14,1,AIUnitDefensive
	@@UnitBasic Unit_Bomber,10,3,AIUnitDefensive
	@@UnitBasic Unit_Bomber,14,3,AIUnitDefensive
	@@UnitBasic Unit_BattleCopter,8,2,AIUnitDefensive
	@@UnitBasic Unit_BattleCopter,16,2,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,14,0,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,10,0,AIUnitDefensive
	@@UnitBasic Unit_BattleShip,9,1,AIUnitDefensive
	@@UnitBasic Unit_BattleShip,15,1,AIUnitDefensive
	@@UnitBasic Unit_Cruiser,10,4,AIUnitDefensive
	@@UnitBasic Unit_Cruiser,14,4,AIUnitDefensive
	@@UnitBasic Unit_Lander,14,5,AIUnitDefensive
	@@UnitBasic Unit_Lander,10,5,AIUnitDefensive
	@@UnitBasic Unit_Sub,9,3,AIUnitDefensive
	@@UnitBasic Unit_Sub,15,3,AIUnitDefensive

	@@UnitArmyStart ArmyBlueMoon
	@@UnitBasic Unit_Infantry,11,22,AIUnitDefensive
	@@UnitBasic Unit_Infantry,13,22,AIUnitDefensive
	@@UnitBasic Unit_Neotank,12,19,AIUnitDefensive
	@@UnitBasic Unit_Neotank,11,20,AIUnitDefensive
	@@UnitBasic Unit_Neotank,13,20,AIUnitDefensive
	@@UnitBasic Unit_APC,12,21,AIUnitDefensive
	@@UnitBasic Unit_Rockets,11,17,AIUnitDefensive
	@@UnitBasic Unit_Rockets,13,17,AIUnitDefensive
	@@UnitBasic Unit_Fighter,10,21,AIUnitDefensive
	@@UnitBasic Unit_Fighter,14,21,AIUnitDefensive
	@@UnitBasic Unit_Bomber,10,19,AIUnitDefensive
	@@UnitBasic Unit_Bomber,14,19,AIUnitDefensive
	@@UnitBasic Unit_BattleCopter,16,20,AIUnitDefensive
	@@UnitBasic Unit_BattleCopter,8,20,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,10,22,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,14,22,AIUnitDefensive
	@@UnitBasic Unit_BattleShip,9,21,AIUnitDefensive
	@@UnitBasic Unit_BattleShip,15,21,AIUnitDefensive
	@@UnitBasic Unit_Cruiser,10,18,AIUnitDefensive
	@@UnitBasic Unit_Cruiser,14,18,AIUnitDefensive
	@@UnitBasic Unit_Lander,10,17,AIUnitDefensive
	@@UnitBasic Unit_Lander,14,17,AIUnitDefensive
	@@UnitBasic Unit_Sub,9,19,AIUnitDefensive
	@@UnitBasic Unit_Sub,15,19,AIUnitDefensive

	@@UnitArmyStart ArmyGreenEarth
	@@UnitBasic Unit_Infantry,24,12,AIUnitDefensive
	@@UnitBasic Unit_Infantry,24,10,AIUnitDefensive
	@@UnitBasic Unit_Neotank,21,11,AIUnitDefensive
	@@UnitBasic Unit_Neotank,22,12,AIUnitDefensive
	@@UnitBasic Unit_Neotank,22,10,AIUnitDefensive
	@@UnitBasic Unit_APC,23,11,AIUnitDefensive
	@@UnitBasic Unit_Rockets,19,10,AIUnitDefensive
	@@UnitBasic Unit_Rockets,19,12,AIUnitDefensive
	@@UnitBasic Unit_Fighter,23,9,AIUnitDefensive
	@@UnitBasic Unit_Fighter,23,13,AIUnitDefensive
	@@UnitBasic Unit_Bomber,21,9,AIUnitDefensive
	@@UnitBasic Unit_Bomber,21,13,AIUnitDefensive
	@@UnitBasic Unit_BattleCopter,22,7,AIUnitDefensive
	@@UnitBasic Unit_BattleCopter,22,15,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,24,9,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,24,13,AIUnitDefensive
	@@UnitBasic Unit_BattleShip,23,8,AIUnitDefensive
	@@UnitBasic Unit_BattleShip,23,14,AIUnitDefensive
	@@UnitBasic Unit_Cruiser,20,9,AIUnitDefensive
	@@UnitBasic Unit_Cruiser,20,13,AIUnitDefensive
	@@UnitBasic Unit_Lander,19,9,AIUnitDefensive
	@@UnitBasic Unit_Lander,19,13,AIUnitDefensive
	@@UnitBasic Unit_Sub,21,8,AIUnitDefensive
	@@UnitBasic Unit_Sub,21,14,AIUnitDefensive

	@@UnitArmyStart ArmyYellowComet
	@@UnitBasic Unit_Infantry,0,12,AIUnitDefensive
	@@UnitBasic Unit_Infantry,0,10,AIUnitDefensive
	@@UnitBasic Unit_Neotank,3,11,AIUnitDefensive
	@@UnitBasic Unit_Neotank,2,12,AIUnitDefensive
	@@UnitBasic Unit_Neotank,2,10,AIUnitDefensive
	@@UnitBasic Unit_APC,1,11,AIUnitDefensive
	@@UnitBasic Unit_Rockets,5,10,AIUnitDefensive
	@@UnitBasic Unit_Rockets,5,12,AIUnitDefensive
	@@UnitBasic Unit_Fighter,1,9,AIUnitDefensive
	@@UnitBasic Unit_Fighter,1,13,AIUnitDefensive
	@@UnitBasic Unit_Bomber,3,9,AIUnitDefensive
	@@UnitBasic Unit_Bomber,3,13,AIUnitDefensive
	@@UnitBasic Unit_BattleCopter,2,7,AIUnitDefensive
	@@UnitBasic Unit_BattleCopter,2,15,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,0,9,AIUnitDefensive
	@@UnitBasic Unit_TransportCopter,0,13,AIUnitDefensive
	@@UnitBasic Unit_BattleShip,1,8,AIUnitDefensive
	@@UnitBasic Unit_BattleShip,1,14,AIUnitDefensive
	@@UnitBasic Unit_Cruiser,4,9,AIUnitDefensive
	@@UnitBasic Unit_Cruiser,4,13,AIUnitDefensive
	@@UnitBasic Unit_Lander,5,9,AIUnitDefensive
	@@UnitBasic Unit_Lander,5,13,AIUnitDefensive
	@@UnitBasic Unit_Sub,3,8,AIUnitDefensive
	@@UnitBasic Unit_Sub,3,14,AIUnitDefensive

	@@UnitListEnd
