; Original offset: 0x084b93f8
C33_5_Event_0a:
	Event_Pause		0
	Event_Audio_Start	0x012e
	Event_Pause		0
	Event_Textbox_SetColour	ArmyOrangeStar
	Event_Textbox_Create	COHachi+IsHappy,Position_Top
	Event_Textbox_SetFace	COHachi+IsHappy
	Event_Textbox_Text	0x0874
	Event_Textbox_SetFace	CONell
	Event_Textbox_Text	0x0875
	Event_Textbox_SetFace	COHachi
	Event_Textbox_Text	0x0876
	Event_Textbox_SetColour	ArmyBlueMoon
	Event_Textbox_SetFace	COColin+IsSad
	Event_Textbox_Text	0x0877
	Event_Textbox_SetColour	ArmyOrangeStar
	Event_Textbox_SetFace	COHachi
	Event_Textbox_Text	0x0878
	Event_Textbox_SetColour	ArmyYellowComet
	Event_Textbox_SetFace	COSensei+IsHappy
	Event_Textbox_Text	0x0879
	Event_Textbox_SetColour	ArmyOrangeStar
	Event_Textbox_SetFace	COHachi
	Event_Textbox_Text	0x087a
	Event_Textbox_SetColour	ArmyYellowComet
	Event_Textbox_SetFace	COSonja
	Event_Textbox_Text	0x087b
	Event_Textbox_SetFace	COKanbei+IsHappy
	Event_Textbox_Text	0x087c
	Event_Textbox_SetColour	ArmyOrangeStar
	Event_Textbox_SetFace	COHachi
	Event_Textbox_Text	0x087d
	Event_Textbox_SetColour	ArmyBlueMoon
	Event_Textbox_SetFace	COOlaf
	Event_Textbox_Text	0x087e
	Event_Textbox_SetFace	COColin
	Event_Textbox_Text	0x087f
	Event_Textbox_SetFace	COGrit
	Event_Textbox_Text	0x0880
	Event_Textbox_SetColour	ArmyOrangeStar
	Event_Textbox_SetFace	COMax
	Event_Textbox_Text	0x0881
	Event_Textbox_SetColour	ArmyBlueMoon
	Event_Textbox_SetFace	COGrit
	Event_Textbox_Text	0x0882
	Event_Textbox_SetColour	ArmyOrangeStar
	Event_Textbox_SetFace	COMax
	Event_Textbox_Text	0x0883
	Event_Textbox_SetFace	COSami
	Event_Textbox_Text	0x0884
	Event_Textbox_SetColour	ArmyYellowComet
	Event_Textbox_SetFace	COSonja+IsHappy
	Event_Textbox_Text	0x0885
	Event_Textbox_SetColour	ArmyOrangeStar
	Event_Textbox_SetFace	COSami
	Event_Textbox_Text	0x0886
	Event_Textbox_SetColour	ArmyYellowComet
	Event_Textbox_SetFace	COSonja+IsHappy
	Event_Textbox_Text	0x0887
	Event_Textbox_SetColour	ArmyGreenEarth
	Event_Textbox_SetFace	CODrake
	Event_Textbox_Text	0x0888
	Event_Textbox_SetFace	COJess+IsHappy
	Event_Textbox_Text	0x0889
	Event_Textbox_SetFace	COEagle+IsHappy
	Event_Textbox_Text	0x088a
	Event_Textbox_SetFace	COJess
	Event_Textbox_Text	0x088b
	Event_Textbox_SetFace	COEagle
	Event_Textbox_Text	0x088c
	Event_Textbox_SetFace	COJess
	Event_Textbox_Text	0x088d
	Event_Textbox_SetFace	CODrake
	Event_Textbox_Text	0x088e
	Event_Textbox_SetColour	ArmyOrangeStar
	Event_Textbox_SetFace	CONell+IsHappy
	Event_Textbox_Text	0x088f
	Event_Textbox_SetFace	COAndy
	Event_Textbox_Text	0x0890
	Event_Textbox_SetFace	COMax
	Event_Textbox_Text	0x0891
	Event_Textbox_SetFace	COHachi+IsHappy
	Event_Textbox_Text	0x0892
	Event_Textbox_SetFace	COSami+IsHappy
	Event_Textbox_Text	0x0893
	Event_Textbox_Clear
	Event_Call		0x084b9958
	Event_Textbox_SetCurrent
	Event_RunASM		0x08045f95
	Event_RunASM		0x08034f8d
	Event_RunASM		0x08045f5d
	Event_End

; blank line