;outrealmmain.asm"
;Defines the text for outrealm COs
	.include "text/outrealmcos/outrealmcco.asm"
	
	.include "text/outrealmcos/awdsnell.asm"
	.include "text/outrealmcos/awdsandy.asm"
	.include "text/outrealmcos/awdsmax.asm"	
	.include "text/outrealmcos/awdssami.asm"
	.include "text/outrealmcos/awdshachi.asm"	
	.include "text/outrealmcos/awdsrachel.asm"
	.include "text/outrealmcos/awdsjake.asm"

	.include "text/outrealmcos/awdsolaf.asm"
	.include "text/outrealmcos/awdsgrit.asm"
	.include "text/outrealmcos/awdscolin.asm"
	.include "text/outrealmcos/awdssasha.asm"

	.include "text/outrealmcos/awdskanbei.asm"
	.include "text/outrealmcos/awdssonja.asm"
	.include "text/outrealmcos/awdssensei.asm"
	.include "text/outrealmcos/awdsgrimm.asm"

	.include "text/outrealmcos/awdseagle.asm"
	.include "text/outrealmcos/awdsdrake.asm"
	.include "text/outrealmcos/awdsjess.asm"
	.include "text/outrealmcos/awdsjavier.asm"
	
	.include "text/outrealmcos/awdsflak.asm"
	.include "text/outrealmcos/awdslash.asm"
	.include "text/outrealmcos/awdsadder.asm"
	.include "text/outrealmcos/awdshawke.asm"
	.include "text/outrealmcos/awdsjugger.asm"
	.include "text/outrealmcos/awdskindle.asm"
	.include "text/outrealmcos/awdskoal.asm"
	.include "text/outrealmcos/awdsvonbolt.asm"
	
	.include "text/outrealmcos/aw1nell.asm"
	.include "text/outrealmcos/aw1andy.asm"
	.include "text/outrealmcos/aw1max.asm"
	.include "text/outrealmcos/aw1sami.asm"
	.include "text/outrealmcos/aw1olaf.asm"
	.include "text/outrealmcos/aw1grit.asm"
	.include "text/outrealmcos/aw1kanbei.asm"
	.include "text/outrealmcos/aw1sonja.asm"
	.include "text/outrealmcos/aw1eagle.asm"
	.include "text/outrealmcos/aw1drake.asm"
	.include "text/outrealmcos/aw1sturm.asm"
	.include "text/outrealmcos/aw1sturmvs.asm"

	
	.include "text/outrealmcos/sfwcaroline.asm"
	.include "text/outrealmcos/sfwbillygates.asm"
	.include "text/outrealmcos/sfwyamamoto.asm"
	.include "text/outrealmcos/ccozed.asm"
;	.include "text/outrealmcos/ccokirby.asm"
	.include "text/outrealmcos/ccovenomadder.asm"
	.include "text/outrealmcos/ccoepoch.asm"
	.include "text/outrealmcos/ccowalter.asm"
	.include "text/outrealmcos/ccoeliwood.asm"
	.include "text/outrealmcos/cconergal.asm"
	.include "text/outrealmcos/ccotransmog.asm"
;Blank Line
