;table_covsmenudescriptions.asm

Table_VersusMenu_Description_Offset:
	.word	String_VsMenu_Nell
	.word	String_VsMenu_Andy
	.word	String_VsMenu_Max
	.word	String_VsMenu_Olaf
	.word	String_VsMenu_Sami
	.word	String_VsMenu_Grit
	.word	String_VsMenu_Kanbei
	.word	String_VsMenu_Sonja
	.word	String_VsMenu_Eagle
	.word	String_VsMenu_Drake
	.word	String_VsMenu_Sturm
	.word	String_VsMenu_Flak
	.word	String_VsMenu_Lash
	.word	String_VsMenu_Adder
	.word	String_VsMenu_Hawke
	.word	String_VsMenu_Hachi
	.word	String_VsMenu_Colin
	.word	String_VsMenu_Jess
	.word	String_VsMenu_Sensei
	.word	String_VsMenu_Andy
	.word	String_VsMenu_Andy
	.word	String_VsMenu_Andy
	.word	String_VsMenu_Andy
	.word	String_VsMenu_Andy
	.word	String_VsMenu_AWDSJake
	.word	String_VsMenu_AWDSRachel
	.word	String_VsMenu_AWDSSasha
	.word	String_VsMenu_AWDSJavier
	.word	String_VsMenu_AWDSGrimm
	.word	String_VsMenu_AWDSJugger
	.word	String_VsMenu_AWDSKoal
	.word	String_VsMenu_AWDSKindle
	.word	String_VsMenu_AWDSVonBolt
	.word	String_VsMenu_AWDSNell
	.word	String_VsMenu_AWDSAndy
	.word	String_VsMenu_AWDSMax
	.word	String_VsMenu_AWDSSami
	.word	String_VsMenu_AWDSHachi
	.word	String_VsMenu_AWDSOlaf
	.word	String_VsMenu_AWDSGrit
	.word	String_VsMenu_AWDSColin
	.word	String_VsMenu_AWDSKanbei
	.word	String_VsMenu_AWDSSonja
	.word	String_VsMenu_AWDSSensei
	.word	String_VsMenu_AWDSEagle
	.word	String_VsMenu_AWDSDrake
	.word	String_VsMenu_AWDSJess
	.word	String_VsMenu_AWDSFlak
	.word	String_VsMenu_AWDSLash
	.word	String_VsMenu_AWDSAdder
	.word	String_VsMenu_AWDSHawke
	.word	String_VsMenu_AW1Sturm
	.word	String_VsMenu_AW1SturmVs
	.word	String_VsMenu_AW1Nell
	.word	String_VsMenu_AW1Andy
	.word	String_VsMenu_AW1Max
	.word	String_VsMenu_AW1Sami
	.word	String_VsMenu_AW1Olaf
	.word	String_VsMenu_AW1Grit
	.word	String_VsMenu_AW1Kanbei
	.word	String_VsMenu_AW1Sonja
	.word	String_VsMenu_AW1Eagle
	.word	String_VsMenu_AW1Drake
	.word	String_VsMenu_SFWCaroline
	.word	String_VsMenu_SFWBillygates
	.word	String_VsMenu_SFWYamamoto
	.word	String_VsMenu_CCOVenomAdder
	.word	String_VsMenu_CCOEpoch
	.word	String_VsMenu_CCOWalter
	.word	String_VsMenu_Andy
	.word	String_VsMenu_CCOEliwood
	.word	String_VsMenu_CCONergal
	.word	String_VsMenu_CCOTransmog
	
